### ISSUE TITLE
Android Asus Zenfone x86 Object Clone is not a function

### ISSUE THREAD

**Issue by zek** [frida/frida-java-bridge#100]
After I run
root@Z00A:/ # /data/local/tmp/frida-server

It started to giving the error below repeatedly.

{"type":"error","description":"TypeError: api.art::mirror::Object::Clone is not a function","stack":"TypeError: api.art::mirror::Object::Clone is not a function\n    at cloneArtMethod (frida/node_modules/frida-java/lib/android.js:735:1)\n    at resolveArtTargetMethodId (frida/node_modules/frida-java/lib/class-factory.js:1653:1)\n    at klass.f (eval at makeMethod (frida/node_modules/frida-java/lib/class-factory.js:1566:1), <anonymous>:1:306)\n    at klass.f (frida/node_modules/frida-java/lib/class-factory.js:1393:1)\n    at klass.sendMessageDelayed.implementation (/internal-agent.js:196:31)\n    at f (eval at implement (frida/node_modules/frida-java/lib/class-factory.js:2103:1), <anonymous>:1:285)","fileName":"frida/node_modules/frida-java/lib/android.js","lineNumber":735,"columnNumber":1}

**Comment by u3978** [comment]
same problem on x86 device

**Comment by BitTheByte** [comment]
Samething
