### ISSUE TITLE
Java Wrapper's getClass() should return Wrapper of 'java.lang.Class'

### ISSUE THREAD

**Issue by gebing** [frida/frida-java-bridge#139]
Java Wrapper's `getClass()` method now return a Wrapper of `java.lang.Object`, which can not invoke `java.lang.Class`'s method, such as `getName()`/`getClassLoader()`. It must be explicitly cast to a wrapper of `java.lang.Class`. Below is the sample:

```
const clazz = Java.use('java.lang.Exception').getClass();
const classLoader = Java.cast(clazz, Java.use('java.lang.Class')).getClassLoader();
```

I digged into source code and found it was caused by below code of `Env.prototype.getTypeName` in `env.js`:

```
if (result === 'java.lang.Class' && !getGenericsInformation) {
  return this.getActualTypeArgument(type);
}
```

The code explicitly convert java.lang.Class to this actual argument type. I do not understand its purpose, but i think this was wrong.

@oleavr

**Comment by gebing** [comment]
Similar case include many method such like Class.getInterfaces().

**Comment by gebing** [comment]
@oleavr 

If you agree with my suggestion, i can modify the code to drop `this.getActualTypeArgument(type)`  and make a pull request for it.

**Comment by oleavr** [comment]
Yes please, let's fix this! 🎉
