### ISSUE TITLE
Java's fields should be accessible even without an instance

### ISSUE THREAD

**Issue by gebing** [frida/frida-java-bridge#143]
Java wrapper object's fields for java class returned by `Java.use` function can not access when it is not an instance. It will throw an exception of `Unable to access instance field without an instance` by the following code of `function addMethodsAndFields ()`:

```
if (this.$handle === undefined)
  throw new Error('Unable to access instance field without an instance');
```

I think the code should be move the field value's getter/setter function, so that the field's other attributes, such as `holder`/`fieldType`/`fieldReturnType`, can be accessed when it is not an instance of class.

@oleavr 
If you agree my suggestion, i can make a pull request.

By the way, if you have time, pls check the pull request of frida/frida-gum#347. It's a bug of `hexdump`.

**Comment by oleavr** [comment]
Sounds like a good idea!
