### ISSUE TITLE
TypeError: undefined not callable (property 'getDataDir' of [object Object])

### ISSUE THREAD

**Issue by alidhkh** [frida/frida-java-bridge#156]
Hi, I have tried a few scripts, and I get this error:

```
TypeError: undefined not callable (property 'getDataDir' of [object Object])
    at [anon] (../../../frida-gum/bindings/gumjs/duktape.c:65012)
    at _ (frida/node_modules/frida-java-bridge/index.js:464)
    at frida/node_modules/frida-java-bridge/index.js:316
    at frida/node_modules/frida-java-bridge/lib/vm.js:11
    at /_java.js:2858
    at frida/node_modules/frida-java-bridge/index.js:287
    at /repl.js:22
```

What could be the cause?

**Comment by oleavr** [comment]
@alidhkh Thanks! I see the issue. We're accidentally using [getDataDir()]( https://developer.android.com/reference/android/content/Context#getDataDir()) which is only available starting with API level 24 (Android 7.0). Will fix.

@srcdes Are you sure you're seeing the same issue and that it's on Android 8.0? Seems impossible that it's the same issue if you're actually testing on 8.0.
