### ISSUE TITLE
Frida Gadget fails on Android API >= 30 due to missing symbols in libart

### ISSUE THREAD

**Issue by BinaryKhaos** [frida/frida-java-bridge#161]
Apparently some functionality from libart has been [removed](https://android.googlesource.com/platform/art/+/fc58809f7b932d86234130be15487017dc37b0cf%5E!) upstream which is required by Frida Gadget, thus the gadget crashes complaining about:

`Frida   : Error: Java API only partially available; please file a bug. Missing: _ZN3art3Dbg9StartJdwpEv, _ZN3art3Dbg8GoActiveEv, _ZN3art3Dbg21RequestDeoptimizationERKNS_21DeoptimizationRequest
E, _ZN3art3Dbg20ManageDeoptimizationEv, _ZN3art3Dbg9gRegistryE`

Frida 12.8.20, tested with a x86_64 API 30 emulator image.

**Comment by oleavr** [comment]
Fixed in d072979, but not yet released. Will take a little time to get it out as I'm currently upgrading Frida's dependencies. In the meantime you can build Frida yourself by modifying `frida-gum/bindings/gumjs/package.json` to use `frida-java-bridge@3.6.11`.

**Comment by BinaryKhaos** [comment]
Thanks for the swift response-- and your stunning work on Frida in general! And sorry I filed the report with the wrong component, still kinda new to Frida and I don't have the full view on its architecture yet.
