### ISSUE TITLE
TypeError: undefined not callable (property 'getEncoded' of [object Object])

### ISSUE THREAD

**Issue by abinpaul1** [frida/frida-java-bridge#165]
I get error when I try to call method of an object.
```
TypeError: undefined not callable (property 'getEncoded' of [object Object])
    at [anon] (../../../frida-gum/bindings/gumjs/duktape.c:67616)
    at /cipher_bevq_react.js:28
    at we (frida/node_modules/frida-java-bridge/lib/class-factory.js:598)
    at frida/node_modules/frida-java-bridge/lib/class-factory.js:581
```

The frida hooking code
```java
Java.perform(function(){

    var SecretKey = Java.use('javax.crypto.SecretKey');

    var target_class = Java.use('com.reactlibrary.securekeystore.RNSecureKeyStoreModule');
    target_class.decryptAesCipherText.overload('javax.crypto.SecretKey','[B').implementation = function(key, array){
        var b = key.getEncoded()
   }
```

Here trying to call `getEncoded` method of `javax.crypto.SecretKey` causes the error
Thanks in advance for the help.

**Comment by oleavr** [comment]
Try `console.log(key.$className);` to check that it is of the expected type and you don't have to `Java.cast()` it.

**Comment by abinpaul1** [comment]
`console.log(key.$className)` gives output as subclass `javax.crypto.spec.SecretKeySpec` and not the interface `javax.crypto.SecretKey`. 

Casting it to `javax.crypto.SecretKeySpec` resolved the issue and enabled the call to the method.
```java
const SecretKeySpec = Java.use('javax.crypto.spec.SecretKeySpec')
const secretKeySpec = Java.cast(key, SecretKeySpec);
const encodedKey = secretKeySpec.getEncoded();
// print the key bytes as hex value
```
Thanks for the help.
Just a follow-up question: Should parameters always be cast explicitly to call its methods?
