### ISSUE TITLE
Java.perform can't use

### ISSUE THREAD

**Issue by sollyu** [frida/frida-java-bridge#166]
hi, i'm use frida-gadget and use apktool modify application ,like:
您好，我正在使用frida-gadet，使用apktool修改了软件的application，如下：

```java
public class SysApp extends Application {
    static {
        System.loadLibrary("frida-gadget");
    }
    public void onCreate() {
        super.onCreate();
    }
}
```

frida-gadget.config.so:

```json
{
  "interaction": {
    "type": "script",
    "path": "libfrida-gadget.bootstrap.js.so"
  }
}
```

libfrida-gadget.bootstrap.js.so: 

```javascript
'use strict';
Java.perform(function () {
      var Log = Java.use("android.util.Log");
      try {
            const context = Java.use('android.app.ActivityThread').currentApplication().getApplicationContext();
      } catch (error) {
            Log.v("LOG:Test", "999" + error);
      }
});
```

i'm read https://github.com/frida/frida-java-bridge/issues/29 and https://github.com/frida/frida/issues/1091 ,but i can not fix it .
我看了https://github.com/frida/frida-java-bridge/issues/29 和https://github.com/frida/frida/issues/1091 这个两个，但是我依然不知道该怎么解决这个问题。

I hope your reply is right
希望得当你们的回复

**Comment by app910** [comment]
解决了没?
