### ISSUE TITLE
Hooking dynamically loaded code in android?

### ISSUE THREAD

**Issue by MitchHS** [frida/frida-java-bridge#177]
My use case is I'm trying to dynamically analyze some malware. Code is packed into a .jar file containing a dex file that is dynamically loaded at runtime using DexClassLoader. 

I have no issues finding the .jar file, but trying to hook a method in the loaded class returns the generic error: "class not found in dex path list". 

Has anyone managed to dynamically hook functions inside classes that are dynamically loaded at runtime? Would be grateful if you could point me in the right direction.

**Comment by monkeylord** [comment]
You should find the classloader that load the code. Then set `Java.classFactory.loder` =  the loader.

**Comment by oleavr** [comment]
The new way is:

```js
var factory = Java.ClassFactory.get(loader);
var MyClass = factory.use('my.Class');
```
