### ISSUE TITLE
Hotspot jvm support: discovered a very nasty bug in connection with method id handling

### ISSUE THREAD

**Issue by Palacee-hun** [frida/frida-java-bridge#198]
I experimented with Java support on hotspot jvm. I found out that Java.use and Java.choose worked fine. But I could not do anything with the class wrappers and instance objects, because when calling any method or getting the value of any field, the target Java app simply quit. In case of method calls, no exceptions, errors, dumps or anything like that were produced. In case of some fields, jvm complained about invalid field id and produced an error log and dump, but they weren't helpful in finding the cause.
Hunting this down seemed very hard, but nevertheless I took the challenge, and fired up Chrome devtools, and thanks to these fantastic tools and the built-in debugging support in V8 runtime, I managed to find the culprit:

in lib/class-factory.js in makeMethodFromSpec function

```
  const methods = overloads.map(params => {
    const type = (params[0] === 's') ? STATIC_METHOD : INSTANCE_METHOD;
    const methodId = ptr(params.substr(1));

    let jsRetType;
    const jsArgTypes = [];
    const handle = env.toReflectedMethod(classHandle, methodId, (type === STATIC_METHOD) ? 1 : 0);
```

and in makeFieldFromSpec function

```
  const type = (spec[2] === 's') ? STATIC_FIELD : INSTANCE_FIELD;
  const id = ptr(spec.substr(3));
  const { $f: factory } = classWrapper;

  let fieldType;
  const field = env.toReflectedField(classHandle, id, (type === STATIC_FIELD) ? 1 : 0);
```

env.toReflectedMethod and env.toReflectedField respectively do not return and crash the jvm due to invalid method id passed in. Cause of the invalid method id lies in the ptr() NativePointer constructors in these code fragments. Method ids are stored in the class model hash table as hexa strings, but they are not prepended with 0x, so ptr() interprets them as decimal strings, and obviously constructs a totally bogus method id which then crashes the jvm.

Method id storing takes place in the C module in lib/class-model.js in model_add_method like this:

```
  value = g_hash_table_lookup (members, key);
  if (value == NULL)
    g_hash_table_insert (members, key, g_strdup_printf ("m:%c%p", type, id));
  else
    g_hash_table_insert (members, key, g_strdup_printf ("%s:%c%p", value, type, id));
```

and analogous code is to be found in model_add_field. So %p drives method id storing, which is by the way an implementation-dependent format specifier.

Prepending 0x to the strings in the cited ptr() constructors fixes the issue for me, and any Java method can be called and any Java field can be obtained flawlessly then.

**Comment by oleavr** [comment]
Thanks, great catch! 😍
