### ISSUE TITLE
Frida server throwing error in Pixel 5 device 

### ISSUE THREAD

**Issue by shruti-94** [frida/frida-java-bridge#200]
I am getting an error while running the frida server on my pixel 5 device. As soon as i ran it, it throws a "**Runtime.jni_ids_indirection**" error and does not works.  I am not sure what this error is about. I tested the same in pixel 4 XL device and works properly without any issues.

Device Info :Pixel 5, Android 10 

<img width="1050" alt="frida-error-pixel5 (1)" src="https://user-images.githubusercontent.com/16492366/103315112-ab501e80-49f2-11eb-9661-b6b077d0b93d.png">

**Comment by oleavr** [comment]
@ArsenyLL Looking at the objdump output and carefully examining the proposed fix by @muhzii, I'm fairly confident that it is the correct fix. Just tagged Frida 14.2.7 with the fix included. Please let me know if it solves the issue for you. (Not able to test this on Pixel 5 as the closest device I've got is a Pixel 3.)

**Comment by nscottsol** [comment]
Yes, just loaded frida-server 14.2.7 on my pixel 5 and so far it's working great. Thanks so much for the quick fix!!
