### ISSUE TITLE
how to direct call original method in CLI

### ISSUE THREAD

**Issue by 327135569** [frida/frida-java-bridge#202]
in Android app, example function
```java
static void test1(){
   return 42;
}
```

in Frida side, i will do this
```js
xxx.test1.implementation = function() {
     return 0;
}

// ok, test1 hooked
xxx.test1();    //will print 0;

//now, is there a way to direct call origin method?

```

**Comment by 327135569** [comment]
i test on frida14 and frida12, and behavor is totally diffrent.

on frida12. above example `xxx.test1` return original value 42; but on frida14 result is 0.

let me CLOSE and READ THE FUCKING SOURCES.

**Comment by SAMOxtan** [comment]
你好，请问你解决这个问题了吗，我现在frida16也不知道怎么调用原方法

**Comment by dreamingtech** [comment]
use rpc.exports to export functions in js file, call rpc.exports.xxx in frida-cli, just as how you call js functions in python
