### ISSUE TITLE
Frida rpc issue

### ISSUE THREAD

**Issue by PriyankaBose** [frida/frida-java-bridge#206]
I have the following code snippet to restart an app if it crashes and continue app exploration from there:
```
def on_kill(crash):
    print("The process got killed")
    device = frida.get_usb_device()
    pid = device.spawn(["org.moire.opensudoku"])
    time.sleep(1)  # Without it Java.perform silently fails
    session = device.attach(pid)
    script = session.create_script(script_cnt)
    script.on('message', on_message)
    print("Debugger should attach")
    device.resume(pid)
    script.load()
    script.exports.enumallclasses()

def on_message(message, payload):
    print(message)


if __name__ == "__main__":

    script_files = ["test_run.js", 'example_import.js', 'exports.js']
    script_cnt = ''
    for name in script_files:
        path_script = os.path.dirname(os.path.abspath(__file__)) + '/' + name
        # print(os.path.dirname(os.path.abspath(__file__)))
        with open(path_script) as f:
            script_cnt += f.read()

        script_cnt += '\n'

    device = frida.get_usb_device()
    pid = device.spawn(["org.moire.opensudoku"])
    time.sleep(1)  # Without it Java.perform silently fails
    session = device.attach(pid)
    device.on('process_crashed', on_kill)
    script = session.create_script(script_cnt)
    script.on('message', on_message)
    print("Debugger should attach")
    device.resume(pid)
    script.load()
    script.exports.enumallclasses()
```

However, the call to `script.exports.enumallclasses()` within the `on_kill` hangs forever. After debugging a bit and looking into the `core.py` file for the frida client, what I understood is that it is stuck at `self.cond.wait()` within the `_rpc_request` function. 
Is this some issue with frida rpc connection or I am missing something?
Please help me. Thanks in advance.

**Comment by oleavr** [comment]
The issue is that callbacks from Frida should never do anything blocking – they should only schedule work on an application thread. This is a limitation of frida-python using Frida's synchronous API. Once we drop support for Python 2, we will be able to move to async/await and switch to the asynchronous Frida API.

Cheers!

**Comment by oleavr** [comment]
Btw, this example shows how one can solve this by using the `Reactor` class from frida-tools:
https://github.com/frida/frida-python/blob/master/examples/child_gating.py
(Just one of many ways obviously, but the one I'd recommend if you're not already using some framework or UI toolkit that has its own reactor.)
