### ISSUE TITLE
Constructing a string array with Frida

### ISSUE THREAD

**Issue by benben30** [frida/frida-java-bridge#255]
I'm trying to call a function with Frida that takes a string array as one of its arguments.

```java
public void coolFunction(long value, String[] strArr);
```

Within Java it gets called like this:

```java
long importantValue = 4L;
String[] importantArr = new String[]{"TEST"};
coolFunction(importantValue, importantArr);
```

The overload looks like this: `.overload('long', '[Ljava.lang.String;')`

I *could* probably create a string array from scratch, but I don't know how to express it in Javascript. What's the Frida equivalent of `new String[]{"TEST"}`?

Because of that I tried to turn an `ArrayList<String>` into a `String[]`, which also wasn't successful.

As far as I can tell there are two simple ways to turn `ArrayList<String>` into `String[]`:

Attempt #1:
```java
List<String> list = new ArrayList<String>();
list.add("TEST");
String[] stringArray = list.toArray(new String[0]);
```

If I try to express it with Javascript it looks like this:

```javascript
var AL_class = Java.use("java.util.ArrayList");
var arrList = AL_class.$new();
arrList.add("TEST");
var stringArray = arrList.toArray(Java.use("[Ljava.lang.String;").$new(0));
```
This fails with the following error message:
```
Error: no supported overloads
```

Attempt #2:
```java
List<String> list = new ArrayList<String>();
list.add("TEST");
Object[] objectArray = list.toArray();
String[] stringArray = (String[]) objectArray;
```

Javascript:
```javascript
var AL_class = Java.use("java.util.ArrayList");
var arrList = AL_class.$new();
arrList.add("TEST");
var arrayButAsObject = arrList.toArray();
var stringArray = Java.cast(arrayButAsObject, "[Ljava.lang.String;");
```

This fails because it assumes that I want to use Javascript's `toArray()` function.

The solution to this problem is probably very simple but I've been stuck here for quite a while now and can't seem to figure it out. Any help would be appreciated.

**Comment by thanhvd-metric** [comment]
I'm having same issue, how you solved this?
