### ISSUE TITLE
how can i use the new version(6.2.3) java bridge with my frida version 15.2.2

### ISSUE THREAD

**Issue by zkywalker** [frida/frida-java-bridge#265]
I see u fix the getPackageInfoNoCheck bug of android 13 in version 6.2.3.
But when i use npm install it, it doesn't seem to work for me.
So how to build this distribution?
thanks a lot

**Comment by Titoot** [comment]
Can you send the error? (and make sure npm/node is up to date)

**Comment by zkywalker** [comment]
> Can you send the error? (and make sure npm/node is up to date)

I turned my device to android 12, so it cant appear again  now:(
But the stack trace show that my frida`s frida-java-bridge version is not 6.2.3, because the trace is change
